CREATE TABLE raw_opportunities
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    short_summary      TEXT,
    news_url           VARCHAR(255)                            NOT NULL,
    source_name        VARCHAR(255)                            NOT NULL,
    screened_relevant  BOOLEAN,
    became_opportunity BOOLEAN                                 NOT NULL,
    found_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_raw_opportunities PRIMARY KEY (id),
    CONSTRAINT uc_raw_opportunities_news_url UNIQUE (news_url)
);

CREATE TABLE opportunities
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    raw_opportunity_id    BIGINT                                  NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    summary               TEXT                                    NOT NULL,
    type                  VARCHAR(255)                            NOT NULL,
    thematic_area         VARCHAR(255),
    modality              VARCHAR(255),
    start_date            DATE,
    end_date              DATE,
    registration_deadline DATE,
    location              VARCHAR(255),
    official_url          VARCHAR(255)                            NOT NULL,
    confidence_score_ai   DOUBLE PRECISION                        NOT NULL,
    source_name           VARCHAR(255)                            NOT NULL,
    image_url             VARCHAR(255),
    is_free               BOOLEAN                                 NOT NULL,
    is_for_all            BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_opportunities PRIMARY KEY (id),
    CONSTRAINT uc_opportunities_raw_opportunity UNIQUE (raw_opportunity_id),
    CONSTRAINT fk_opportunities_on_raw_opportunity FOREIGN KEY (raw_opportunity_id) REFERENCES raw_opportunities (id)
);

CREATE TABLE opportunity_target_audiences
(
    opportunity_id  BIGINT       NOT NULL,
    target_audience VARCHAR(255) NOT NULL,
    CONSTRAINT fk_opportunity_target_audiences_on_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (id)
);

CREATE TABLE user_help
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    suggestion TEXT                                    NOT NULL,
    user_email VARCHAR(255),
    CONSTRAINT pk_user_help PRIMARY KEY (id)
);
