CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE opportunities
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    raw_opportunity_id    BIGINT                                  NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    summary               TEXT                                    NOT NULL,
    type                  VARCHAR(255)                            NOT NULL,
    thematic_area         VARCHAR(255),
    modality              VARCHAR(255),
    start_date            date,
    end_date              date,
    registration_deadline date,
    location              VARCHAR(255),
    official_url          VARCHAR(255)                            NOT NULL,
    confidence_score_ai   DOUBLE PRECISION                        NOT NULL,
    source_name           VARCHAR(255)                            NOT NULL,
    image_url             VARCHAR(255),
    is_free               BOOLEAN                                 NOT NULL,
    is_for_all            BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_opportunities PRIMARY KEY (id)
);

CREATE TABLE opportunity_target_audiences
(
    opportunity_id  BIGINT NOT NULL,
    target_audience VARCHAR(255)
);

CREATE TABLE raw_opportunities
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    short_summary      TEXT,
    news_url           VARCHAR(255)                            NOT NULL,
    source_name        VARCHAR(255)                            NOT NULL,
    screened_relevant  BOOLEAN,
    is_invalid         BOOLEAN,
    became_opportunity BOOLEAN                                 NOT NULL,
    found_at           TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_raw_opportunities PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

ALTER TABLE opportunities
    ADD CONSTRAINT uc_opportunities_raw_opportunity UNIQUE (raw_opportunity_id);

ALTER TABLE raw_opportunities
    ADD CONSTRAINT uc_raw_opportunities_news_url UNIQUE (news_url);

ALTER TABLE opportunities
    ADD CONSTRAINT FK_OPPORTUNITIES_ON_RAW_OPPORTUNITY FOREIGN KEY (raw_opportunity_id) REFERENCES raw_opportunities (id);

ALTER TABLE opportunity_target_audiences
    ADD CONSTRAINT fk_opportunity_target_audiences_on_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);