-- ==============================================================================
-- Migration V5: Criação das tabelas de Usuários, Tokens de Renovação (Refresh Tokens)
-- e Histórico de Execuções do Pipeline (Pipeline Runs)
-- ==============================================================================

-- 1. Tabela de Usuários do Sistema (autenticados via Google OAuth2)
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    avatar_url  VARCHAR(500),
    role        VARCHAR(50)                             NOT NULL DEFAULT 'ROLE_USER',
    password_hash VARCHAR(255),
    google_id   VARCHAR(255),
    is_active   BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT uc_users_google_id UNIQUE (google_id)
);

CREATE INDEX idx_users_email ON users (email);

-- 2. Tabela de Refresh Tokens com Hash Criptográfico (Proteção de Sessão e RTR)
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token_hash VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uc_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- 3. Tabela de Histórico de Execução do Pipeline (Observabilidade e Métricas)
CREATE TABLE pipeline_runs
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    started_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finished_at               TIMESTAMP WITHOUT TIME ZONE,
    status                    VARCHAR(50)                             NOT NULL, -- 'RUNNING', 'SUCCESS', 'FAILED'
    collected_count           INT                                     NOT NULL DEFAULT 0,
    screening_relevant_count  INT                                     NOT NULL DEFAULT 0,
    extraction_relevant_count INT                                     NOT NULL DEFAULT 0,
    failures_count            INT                                     NOT NULL DEFAULT 0,
    duration_ms               BIGINT,
    error_message             TEXT,
    CONSTRAINT pk_pipeline_runs PRIMARY KEY (id)
);

CREATE INDEX idx_pipeline_runs_started_at ON pipeline_runs (started_at DESC);

-- 4. Associação de Oportunidades Brutas à Rodada do Pipeline em que foram coletadas
ALTER TABLE raw_opportunities
    ADD COLUMN pipeline_run_id BIGINT;

ALTER TABLE raw_opportunities
    ADD CONSTRAINT fk_raw_opportunities_on_pipeline_run
        FOREIGN KEY (pipeline_run_id) REFERENCES pipeline_runs (id) ON DELETE SET NULL;

CREATE INDEX idx_raw_opportunities_pipeline_run_id ON raw_opportunities (pipeline_run_id);
