CREATE TABLE raw_opportunities
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    short_summary       TEXT,
    source_url          VARCHAR(255)                            NOT NULL,
    source_name         VARCHAR(255)                            NOT NULL,
    screened_relevant   BOOLEAN,
    probable_type       VARCHAR(255),
    screening_reasoning TEXT,
    became_opportunity  BOOLEAN                                 NOT NULL,
    found_at            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_raw_opportunities PRIMARY KEY (id)
);

ALTER TABLE raw_opportunities
    ADD CONSTRAINT uc_raw_opportunities_source_url UNIQUE (source_url);

CREATE TABLE opportunities
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    raw_opportunity_id    BIGINT                                  NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    summary               TEXT                                    NOT NULL,
    type                  VARCHAR(255)                            NOT NULL,
    modality              VARCHAR(255),
    event_date            date,
    registration_deadline date,
    location              VARCHAR(255),
    official_url          VARCHAR(255)                            NOT NULL,
    confidence_score_ai   DOUBLE PRECISION                        NOT NULL,
    source_name           VARCHAR(255)                            NOT NULL,
    created_at            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_opportunities PRIMARY KEY (id)
);

ALTER TABLE opportunities
    ADD CONSTRAINT uc_opportunities_raw_opportunity UNIQUE (raw_opportunity_id);

ALTER TABLE opportunities
    ADD CONSTRAINT FK_OPPORTUNITIES_ON_RAW_OPPORTUNITY FOREIGN KEY (raw_opportunity_id) REFERENCES raw_opportunities (id);

CREATE TABLE opportunity_target_audiences
(
    opportunity_id  BIGINT NOT NULL,
    target_audience VARCHAR(255) NOT NULL,
    CONSTRAINT pk_opportunity_target_audiences PRIMARY KEY (opportunity_id, target_audience)

);

ALTER TABLE opportunity_target_audiences
    ADD CONSTRAINT fk_opportunity_target_audiences_on_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (id);

CREATE TABLE opportunity_thematic_areas
(
    opportunity_id BIGINT NOT NULL,
    thematic_area  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_opportunity_thematic_areas PRIMARY KEY (opportunity_id, thematic_area)
);

ALTER TABLE opportunity_thematic_areas
    ADD CONSTRAINT fk_opportunity_thematic_areas_on_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (id);